version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      mynetwork:
        ipv4_address: 172.19.0.2

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8082:80"
    networks:
      mynetwork:
        ipv4_address: 172.19.0.3

  web:
    build: .
    container_name: web_container
    ports:
      - "8083:80"
    volumes:
      - ./www:/var/www/html
    networks:
      mynetwork:
        ipv4_address: 172.19.0.4

networks:
  mynetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

volumes:
  postgres_data:
